/** Old /blogs/<slug> URLs from the static site — not migrated 1:1 to Astro. */
export const LEGACY_BLOG_SLUGS = new Set([
  'compta-cgnc',
  'compta-cloture-checklist',
  'compta-gestion-financiere-pme',
  'compta-immobilisations',
  'compta-provisions',
  'compta-stocks',
  'compta-supervision-vs-tenue',
  'compta-tresorerie',
  'creer-capital-social',
  'creer-dissolution',
  'creer-domiciliation',
  'creer-formalites-post-creation',
  'creer-sa-sarl-sas',
  'creer-succursale',
  'expat-compte-devises',
  'expat-convention-franco-marocaine',
  'expat-due-diligence',
  'expat-rapatriement-benefices',
  'expat-sci-maroc',
  'expat-statut-resident-non-resident',
  'fiscalite-2026-01-is-acomptes',
  'fiscalite-2026-02-simpl-impots-guide',
  'fiscalite-2026-03-controle-fiscal-dgi',
  'fiscalite-2026-04-taxe-professionnelle',
  'fiscalite-2026-05-retenues-source',
  'fiscalite-2026-06-optimisation-fiscale-legale',
  'fiscalite-2026-07-liasse-fiscale',
  'fiscalite-2026-08-tva-regimes',
  'fisc-associations-fiscalite',
  'fisc-auto-entrepreneur',
  'fisc-cotisation-minimale',
  'fisc-credit-tva',
  'fisc-dividendes',
  'fisc-droits-enregistrement',
  'fisc-ir-barème',
  'fisc-ir-professionnel',
  'fisc-prescription-fiscale',
  'fisc-prix-transfert',
  'fisc-revenus-fonciers',
  'fisc-tsava',
  'fisc-tsc',
  'fisc-tva-secteurs-specifiques',
  'fisc-zones-acceleration',
  'juridique-bail-commercial',
  'juridique-code-travail-employeurs-etrangers',
  'juridique-contentieux-fiscal',
  'juridique-holding',
  'juridique-marque-ompic',
  'paie-amo',
  'paie-cnss-plafonds-2026',
  'paie-conges-payes',
  'paie-contrat-travail',
  'paie-damancom-guide',
  'paie-ir-damancom-reconciliation',
  'paie-licenciement',
  'paie-mutuelle-avantages-sociaux',
  'paie-net-a-payer',
  'paie-premier-salarie',
]);

/** Best-match targets for high-intent legacy slugs; others fall back to /blog. */
const LEGACY_BLOG_TARGETS: Record<string, string> = {
  'compta-gestion-financiere-pme': '/services/gestion-financiere',
  'compta-supervision-vs-tenue': '/services/supervision-comptable',
  'creer-capital-social': '/blog/creer-sarl-tanger-2026',
  'creer-dissolution': '/services/travaux-juridiques',
  'creer-domiciliation': '/blog/domiciliation-societe-tanger',
  'creer-formalites-post-creation': '/blog/creer-sarl-tanger-2026',
  'creer-sa-sarl-sas': '/blog/sarlau-vs-sarl-vs-sas',
  'creer-succursale': '/services/creation-entreprise',
  'expat-compte-devises': '/blog/expat-francais-investir-tanger',
  'expat-convention-franco-marocaine': '/blog/expat-francais-investir-tanger',
  'expat-due-diligence': '/blog/expat-francais-investir-tanger',
  'expat-rapatriement-benefices': '/blog/expat-francais-investir-tanger',
  'expat-sci-maroc': '/expat',
  'expat-statut-resident-non-resident': '/blog/expat-francais-investir-tanger',
  'fiscalite-2026-01-is-acomptes': '/blog/fiscalite-2026-acomptes-is',
  'fiscalite-2026-02-simpl-impots-guide': '/services/simpl-impots-dgi',
  'fiscalite-2026-03-controle-fiscal-dgi': '/blog/controle-fiscal-tanger-comment-se-preparer',
  'fiscalite-2026-06-optimisation-fiscale-legale': '/blog/reforme-is-2026-pme-tanger',
  'fiscalite-2026-08-tva-regimes': '/blog/tva-credit-remboursement-2026',
  'fisc-auto-entrepreneur': '/auto-entrepreneur-maroc',
  'fisc-credit-tva': '/blog/tva-credit-remboursement-2026',
  'fisc-ir-barème': '/outils/simulateur-ir',
  'fisc-tva-secteurs-specifiques': '/blog/tva-credit-remboursement-2026',
  'fisc-zones-acceleration': '/blog/zones-franches-tanger-comparatif',
  'juridique-contentieux-fiscal': '/blog/controle-fiscal-tanger-comment-se-preparer',
  'paie-cnss-plafonds-2026': '/blog/damancom-cnss-guide-2026',
  'paie-damancom-guide': '/blog/damancom-cnss-guide-2026',
  'paie-ir-damancom-reconciliation': '/blog/damancom-cnss-guide-2026',
  'paie-premier-salarie': '/services/paie-grh',
};

export function legacyBlogRedirect(pathname: string): string | null {
  const m = pathname.match(/^\/(?:blogs|blog)\/([^/]+)$/);
  if (!m) return null;
  const slug = decodeURIComponent(m[1]);
  if (!LEGACY_BLOG_SLUGS.has(slug)) return null;
  return LEGACY_BLOG_TARGETS[slug] ?? '/blog';
}
